# Generated by Django 4.2.2 on 2023-06-10 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='last_karma',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последнее спасибо'),
        ),
    ]
