# Generated by Django 4.2.2 on 2023-06-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0002_discorduser_last_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='karma',
            field=models.FloatField(default=0, verbose_name='Карма'),
        ),
    ]
